export const getAllWalletCategoriesParams = {
  wallets: [
    {
      amount: 3076.96,
      blackListedVendors: [],
      brandingColor: "#E57370",
      categories: [
        {
          id: "gym_and_fitness",
          name: "Gym & Fitness",
          subcategories: [
            {
              eligible: true,
              value: "personal_training",
              _id: "600a53b79dc3017cc561768a",
            },
            { eligible: true, value: "gym", _id: "600a53b79dc3017cc561768b" },
            { eligible: true, value: "fitness_class", _id: "600a53b79dc3017cc561768c" },
            { eligible: true, value: "fitness_others", _id: "600a53b79dc3017cc561768d" },
          ],
          _id: "600a53b79dc3017cc5617689",
        },
        {
          id: "sports_and_activities",
          name: "Sports & Activities",
          subcategories: [
            {
              eligible: true,
              value: "ski_snowboard_ticket",
              _id: "600a53b79dc3017cc561768f",
            },
            { eligible: true, value: "athletic_event_fee", _id: "600a53b79dc3017cc5617690" },
            { eligible: true, value: "sports_league_fee", _id: "600a53b79dc3017cc5617691" },
          ],
          _id: "600a53b79dc3017cc561768e",
        },
        {
          id: "digital_health_apps",
          name: "Digital Health Apps",
          subcategories: [
            { eligible: true, value: "meditation_app", _id: "600a53b79dc3017cc5617693" },
            { eligible: true, value: "seep_aid_app", _id: "600a53b79dc3017cc5617694" },
            { eligible: true, value: "fitness_app", _id: "600a53b79dc3017cc5617695" },
          ],
          _id: "600a53b79dc3017cc5617692",
        },
        {
          id: "equipment",
          name: "Equipment",
          subcategories: [
            { eligible: true, value: "sports_equipment", _id: "600a53b79dc3017cc5617697" },
            {
              eligible: true,
              value: "fitness_equipment",
              _id: "600a53b79dc3017cc5617698",
            },
            {
              eligible: true,
              value: "equipment_others",
              _id: "600a53b79dc3017cc5617699",
            },
            {
              eligible: true,
              value: "equipment_rental",
              _id: "600a53b79dc3017cc561769a",
            },
            {
              eligible: false,
              value: "motorized_vehicles",
              _id: "600a53b79dc3017cc561769b",
            },
          ],
          _id: "600a53b79dc3017cc5617696",
        },
        {
          id: "general_health",
          name: "General Health",
          subcategories: [
            { _id: "600a53b79dc3017cc561769d", value: "acupuncture", eligible: false },
            { _id: "600a53b79dc3017cc561769e", value: "massage_therapy", eligible: true },
            { _id: "600a53b79dc3017cc561769f", value: "alternative_health", eligible: true },
            { _id: "600a53b79dc3017cc56176a0", value: "spa_sauna", eligible: true },
            { _id: "600a53b79dc3017cc56176a1", value: "smoking_cessation", eligible: true },
            { _id: "600a53b79dc3017cc56176a2", value: "weight_management", eligible: true },
            { _id: "600a53b79dc3017cc56176a3", value: "primary_care_substitute", eligible: false },
            { _id: "600a53b79dc3017cc56176a4", value: "general_health_others", eligible: false },
            { _id: "600a53b79dc3017cc56176a5", value: "meditation", eligible: true },
            { _id: "600a53b79dc3017cc56176a6", value: "mental_health_consulting", eligible: true },
          ],
          _id: "600a53b79dc3017cc561769c",
        },
        {
          id: "smart_devices",
          name: "Smart Devices",
          subcategories: [
            { _id: "600a53b79dc3017cc56176a8", value: "smart_watch", eligible: false },
            { _id: "600a53b79dc3017cc56176a9", value: "fitness_tracker", eligible: true },
            { _id: "600a53b79dc3017cc56176aa", value: "sleep_tracker", eligible: true },
            { _id: "600a53b79dc3017cc56176ab", value: "body_scale", eligible: true },
          ],
          _id: "600a53b79dc3017cc56176a7",
        },
        {
          id: "nutrition",
          name: "Nutrition",
          subcategories: [
            { _id: "600a53b79dc3017cc56176ad", value: "food", eligible: false },
            { _id: "600a53b79dc3017cc56176ae", value: "convenience_food", eligible: false },
            { _id: "600a53b79dc3017cc56176af", value: "supplements", eligible: false },
          ],
          _id: "600a53b79dc3017cc56176ac",
        },
        {
          id: "others",
          name: "Others",
          subcategories: [
            { _id: "600a53b79dc3017cc56176b1", value: "personal_enrichment", eligible: false },
            { _id: "600a53b79dc3017cc56176b2", value: "clothes", eligible: false },
            { _id: "600a53b79dc3017cc56176b3", value: "shoes", eligible: false },
            { _id: "600a53b79dc3017cc56176b4", value: "books_magazines", eligible: false },
          ],
          _id: "600a53b79dc3017cc56176b0",
        },
      ],
      companyWalletConfigurationId: "twic_wellness",
      defaultCategories: [
        "gym",
        "massage",
        "wearables",
        "testing_kits",
        "meditation_class",
        "digital_health_apps",
        "nutrition_programs",
        "weight_loss_programs",
        "fitness_classes",
        "personal_training",
        "sports_club_membership",
        "martial_arts",
        "stress_management_program",
        "sleep_management_program",
        "smoking_cessation_program",
        "health_programs",
        "mindfulness",
        "gym_and_fitness",
        "sports_and_activities",
        "smart_devices",
        "home_office_equipment",
        "parenting",
        "nutrition",
      ],
      description: "Take care of your health and wellbeing",
      expiredAmount: 3076.96,
      expiredDate: "Feb 21, 2021",
      fundsExpireDays: -117,
      isTwicCardPaymentAllowed: true,
      maxAmount: 3076.96,
      name: "wellness wallet",
      renewedAmount: 50,
      renewedDate: "Feb 22, 2021",
      unit: "$",
      walletId: "twic_max_account_wallet_01",
      walletTypeId: "wellness",
    },
  ],
  categoriesList: [
    { active: true, id: "gym_and_fitness", image_url: "https://storage.googleapis.com/assets.twicapp-production.twic.ai/category/gym_and_fitness.jpg", title: "Gym & Fitness", wallet_type: "wellness" },
    { active: true, id: "sports_and_activities", image_url: "https://storage.googleapis.com/assets.twicapp-production.twic.ai/category/sports_activities.jpg", title: "Sports & Activities", wallet_type: "wellness" },
  ],
};
export const AllWalletCategoriesResponse = [
  {
    id: "gym_and_fitness",
    title: "Gym & Fitness",
    subcategories: [
      {
        eligible: true,
        value: "personal_training",
        _id: "600a53b79dc3017cc561768a",
      },
      {
        eligible: true,
        value: "gym",
        _id: "600a53b79dc3017cc561768b",
      },
      {
        eligible: true,
        value: "fitness_class",
        _id: "600a53b79dc3017cc561768c",
      },
      {
        eligible: true,
        value: "fitness_others",
        _id: "600a53b79dc3017cc561768d",
      },
    ],
    active: true,
    categoryAlias: "",
    wallet_type: "wellness",
  },
  {
    id: "sports_and_activities",
    title: "Sports & Activities",
    subcategories: [
      {
        eligible: true,
        value: "ski_snowboard_ticket",
        _id: "600a53b79dc3017cc561768f",
      },
      {
        eligible: true,
        value: "athletic_event_fee",
        _id: "600a53b79dc3017cc5617690",
      },
      {
        eligible: true,
        value: "sports_league_fee",
        _id: "600a53b79dc3017cc5617691",
      },
    ],
    active: true,
    categoryAlias: "",
    wallet_type: "wellness",
  },
  {
    id: "digital_health_apps",
    title: "Digital Health Apps",
    subcategories: [
      {
        eligible: true,
        value: "meditation_app",
        _id: "600a53b79dc3017cc5617693",
      },
      {
        eligible: true,
        value: "seep_aid_app",
        _id: "600a53b79dc3017cc5617694",
      },
      {
        eligible: true,
        value: "fitness_app",
        _id: "600a53b79dc3017cc5617695",
      },
    ],
    active: true,
    categoryAlias: "",
    wallet_type: "wellness",
  },
  {
    id: "equipment",
    title: "Equipment",
    subcategories: [
      {
        eligible: true,
        value: "sports_equipment",
        _id: "600a53b79dc3017cc5617697",
      },
      {
        eligible: true,
        value: "fitness_equipment",
        _id: "600a53b79dc3017cc5617698",
      },
      {
        eligible: true,
        value: "equipment_others",
        _id: "600a53b79dc3017cc5617699",
      },
      {
        eligible: true,
        value: "equipment_rental",
        _id: "600a53b79dc3017cc561769a",
      },
      {
        eligible: false,
        value: "motorized_vehicles",
        _id: "600a53b79dc3017cc561769b",
      },
    ],
    active: true,
    categoryAlias: "",
    wallet_type: "wellness",
  },
  {
    id: "general_health",
    title: "General Health",
    subcategories: [
      {
        _id: "600a53b79dc3017cc561769d",
        value: "acupuncture",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc561769e",
        value: "massage_therapy",
        eligible: true,
      },
      {
        _id: "600a53b79dc3017cc561769f",
        value: "alternative_health",
        eligible: true,
      },
      {
        _id: "600a53b79dc3017cc56176a0",
        value: "spa_sauna",
        eligible: true,
      },
      {
        _id: "600a53b79dc3017cc56176a1",
        value: "smoking_cessation",
        eligible: true,
      },
      {
        _id: "600a53b79dc3017cc56176a2",
        value: "weight_management",
        eligible: true,
      },
      {
        _id: "600a53b79dc3017cc56176a3",
        value: "primary_care_substitute",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc56176a4",
        value: "general_health_others",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc56176a5",
        value: "meditation",
        eligible: true,
      },
      {
        _id: "600a53b79dc3017cc56176a6",
        value: "mental_health_consulting",
        eligible: true,
      },
    ],
    active: true,
    categoryAlias: "",
    wallet_type: "wellness",
  },
  {
    id: "smart_devices",
    title: "Smart Devices",
    subcategories: [
      {
        _id: "600a53b79dc3017cc56176a8",
        value: "smart_watch",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc56176a9",
        value: "fitness_tracker",
        eligible: true,
      },
      {
        _id: "600a53b79dc3017cc56176aa",
        value: "sleep_tracker",
        eligible: true,
      },
      {
        _id: "600a53b79dc3017cc56176ab",
        value: "body_scale",
        eligible: true,
      },
    ],
    active: true,
    categoryAlias: "",
    wallet_type: "wellness",
  },
  {
    id: "nutrition",
    title: "Nutrition",
    subcategories: [
      {
        _id: "600a53b79dc3017cc56176ad",
        value: "food",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc56176ae",
        value: "convenience_food",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc56176af",
        value: "supplements",
        eligible: false,
      },
    ],
    active: true,
    categoryAlias: "",
    wallet_type: "wellness",
  },
  {
    id: "others",
    title: "Others",
    subcategories: [
      {
        _id: "600a53b79dc3017cc56176b1",
        value: "personal_enrichment",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc56176b2",
        value: "clothes",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc56176b3",
        value: "shoes",
        eligible: false,
      },
      {
        _id: "600a53b79dc3017cc56176b4",
        value: "books_magazines",
        eligible: false,
      },
    ],
    active: true,
    categoryAlias: "",
    wallet_type: "wellness",
  },
];

export const formattedVendorsHits = [
  {
    available_countries: ["us"],
    categories: ["wearables"],
    coupon_code_locations: [],
    created: "2021-01-22T04:25:28.123Z",
    id: "fitbit_fitbit_charge3_black",
    is_featured: false,
    is_new: true,
    is_pricing_plan_available: false,
    is_product_active: true,
    is_sales_tax_required: true,
    is_shipping_required: true,
    is_vendor_active: true,
    num_of_purchase: 1,
    objectID: "fitbit_fitbit_charge3_black",
    product_id: "fitbit_charge3_black",
    product_image_url: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_tn_2.png",
    product_instruction_image: [
      "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_product_1.png",
      "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_product_1.2.png",
      "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_product_1.3.png",
    ],
    product_title: "Fitbit Charge 3 - Black",
    subcategories: ["fitness_tracker"],
    term: "one_time",
    usd_msrp: 150,
    usd_special_price: 145,
    vendor_id: "fitbit",
    vendor_logo_url: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_vendor_2.png",
    vendor_title: "Fitbit",
    _highlightResult: {
      created: { value: "2021-01-22T04:25:28.123Z", matchLevel: "none", matchedWords: [] },
      num_of_purchase: { value: "1", matchLevel: "none", matchedWords: [] },
      usd_msrp: { value: "150", matchLevel: "none", matchedWords: [] },
      usd_special_price: { value: "145", matchLevel: "none", matchedWords: [] },
      vendor_id: { value: "fitbit", matchLevel: "none", matchedWords: [] },
    },
  },
  {
    available_countries: ["us"],
    categories: ["wearables"],
    coupon_code_locations: [],
    created: "2021-01-22T04:25:28.122Z",
    id: "fitbit_no_sales_tax_fitbit_charge3_black",
    is_featured: false,
    is_new: true,
    is_pricing_plan_available: false,
    is_product_active: true,
    is_sales_tax_required: false,
    is_shipping_required: false,
    is_vendor_active: true,
    num_of_purchase: 0,
    objectID: "fitbit_no_sales_tax_fitbit_charge3_black",
    product_id: "fitbit_charge3_black",
    product_image_url: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_tn_2.png",
    product_instruction_image: [
      "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_product_1.png",
      "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_product_1.2.png",
      "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_product_1.3.png",
    ],
    product_title: "Fitbit Charge 3 - Black",
    subcategories: ["fitness_tracker"],
    term: "one_time",
    usd_msrp: 150,
    usd_special_price: 145,
    vendor_id: "fitbit_no_sales_tax",
    vendor_logo_url: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_vendor_2.png",
    vendor_title: "Fitbit",
    _highlightResult: {
      created: { value: "2021-01-22T04:25:28.122Z", matchLevel: "none", matchedWords: [] },
      num_of_purchase: { value: "0", matchLevel: "none", matchedWords: [] },
      usd_msrp: { value: "150", matchLevel: "none", matchedWords: [] },
      usd_special_price: { value: "145", matchLevel: "none", matchedWords: [] },
      vendor_id: { value: "fitbit_no_sales_tax", matchLevel: "none", matchedWords: [] },
    },
  },
  {
    available_countries: ["us", "gb"],
    categories: ["digital_health_apps", "mindfulness"],
    coupon_code_available: true,
    coupon_code_locations: [],
    created: "2017-06-08T16:01:00.135Z",
    id: "calm_annual_membership",
    is_featured: false,
    is_new: true,
    is_pricing_plan_available: true,
    is_product_active: true,
    is_shipping_required: false,
    is_vendor_active: true,
    num_of_purchase: 0,
    objectID: "calm_annual_membership",
    product_id: "annual_membership",
    product_image_url: "https://storage.googleapis.com/assets.twicapp-production.twic.ai/vendors/calm/Vendor%20Cover_Calm.png",
    product_instruction_image: ["https://storage.googleapis.com/assets.twicapp-production.twic.ai/vendors/calm/Calm_product_1.png", "https://storage.googleapis.com/assets.twicapp-production.twic.ai/vendors/calm/Calm_product_2.png"],
    product_title: "Annual Membership",
    subcategories: ["meditation_app"],
    term: "one_time",
    usd_msrp: 70,
    usd_special_price: 65,
    vendor_id: "calm",
    vendor_logo_url: "https://storage.googleapis.com/assets.twicapp-production.twic.ai/vendors/calm/Vendor%20Cover_Calm.png",
    vendor_title: "Calm",
    _highlightResult: {
      created: { value: "2017-06-08T16:01:00.135Z", matchLevel: "none", matchedWords: [] },
      num_of_purchase: { value: "0", matchLevel: "none", matchedWords: [] },
      usd_msrp: { value: "70", matchLevel: "none", matchedWords: [] },
      usd_special_price: { value: "65", matchLevel: "none", matchedWords: [] },
      vendor_id: { value: "calm", matchLevel: "none", matchedWords: [] },
    },
  },
  {
    available_countries: ["us"],
    categories: ["gym"],
    coupon_code_locations: [],
    created: "2021-01-22T04:25:28.118Z",
    id: "517ffe19-ec92-4481-a0f0-0f7f9e63e329_club_sports",
    is_featured: false,
    is_new: true,
    is_pricing_plan_available: false,
    is_product_active: true,
    is_shipping_required: false,
    is_vendor_active: true,
    num_of_purchase: 0,
    objectID: "517ffe19-ec92-4481-a0f0-0f7f9e63e329_club_sports",
    product_id: "club_sports",
    product_image_url: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/24_hour_fitness/24hourfit_tn_1.png",
    product_instruction_image: ["https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/24_hour_fitness/24hourfit_product_1.png"],
    product_title: "Club Sport",
    subcategories: ["gym"],
    term: "monthly",
    usd_msrp: 35,
    usd_special_price: 30,
    vendor_id: "517ffe19-ec92-4481-a0f0-0f7f9e63e329",
    vendor_logo_url: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/24_hour_fitness/24hourfit_vendor_1.png",
    vendor_title: "24 Hour Fitness",
    _highlightResult: {
      created: { value: "2021-01-22T04:25:28.118Z", matchLevel: "none", matchedWords: [] },
      num_of_purchase: { value: "0", matchLevel: "none", matchedWords: [] },
      usd_msrp: { value: "35", matchLevel: "none", matchedWords: [] },
      usd_special_price: { value: "30", matchLevel: "none", matchedWords: [] },
      vendor_id: { value: "517ffe19-ec92-4481-a0f0-0f7f9e63e329", matchLevel: "none", matchedWords: [] },
    },
  },
];
export const formattedVendorsResponse = [
  {
    availableCountries: ["us"],
    categories: ["wearables"],
    subcategories: ["fitness_tracker"],
    id: "fitbit_fitbit_charge3_black",
    imageUri: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_product_1.png",
    isOneTimeProduct: true,
    priceLimitLower: 145,
    priceLimitUpper: 150,
    productId: "fitbit_charge3_black",
    subtitle: "Fitbit",
    title: "Fitbit Charge 3 - Black",
    vendorId: "fitbit",
  },
  {
    availableCountries: ["us"],
    categories: ["wearables"],
    subcategories: ["fitness_tracker"],
    id: "fitbit_no_sales_tax_fitbit_charge3_black",
    imageUri: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/fitbit/Fitbit_product_1.png",
    isOneTimeProduct: true,
    priceLimitLower: 145,
    priceLimitUpper: 150,
    productId: "fitbit_charge3_black",
    subtitle: "Fitbit",
    title: "Fitbit Charge 3 - Black",
    vendorId: "fitbit_no_sales_tax",
  },
  {
    availableCountries: ["us", "gb"],
    categories: ["digital_health_apps", "mindfulness"],
    subcategories: ["meditation_app"],
    id: "calm_annual_membership",
    imageUri: "https://storage.googleapis.com/assets.twicapp-production.twic.ai/vendors/calm/Calm_product_1.png",
    isOneTimeProduct: true,
    priceLimitLower: 65,
    priceLimitUpper: 70,
    productId: "annual_membership",
    subtitle: "Calm",
    title: "Annual Membership",
    vendorId: "calm",
  },
  {
    availableCountries: ["us"],
    categories: ["gym"],
    subcategories: ["gym"],
    id: "517ffe19-ec92-4481-a0f0-0f7f9e63e329_club_sports",
    imageUri: "https://s3-us-west-1.amazonaws.com/twic.ai/vendor_assets/24_hour_fitness/24hourfit_product_1.png",
    isOneTimeProduct: false,
    priceLimitLower: 30,
    priceLimitUpper: 35,
    productId: "club_sports",
    subtitle: "24 Hour Fitness",
    title: "Club Sport",
    vendorId: "517ffe19-ec92-4481-a0f0-0f7f9e63e329",
  },
];
export const formattedSubCategoriesParams = {
  wallet: {
    amount: 3076.96,
    blackListedVendors: [],
    brandingColor: "#E57370",
    categories: [
      {
        id: "gym_and_fitness",
        name: "Gym & Fitness",
        subcategories: [
          {
            eligible: true,
            value: "personal_training",
            _id: "600a53b79dc3017cc561768a",
          },
          { eligible: true, value: "gym", _id: "600a53b79dc3017cc561768b" },
          { eligible: true, value: "fitness_class", _id: "600a53b79dc3017cc561768c" },
          { eligible: true, value: "fitness_others", _id: "600a53b79dc3017cc561768d" },
        ],
        _id: "600a53b79dc3017cc5617689",
      },
      {
        id: "sports_and_activities",
        name: "Sports & Activities",
        subcategories: [
          {
            eligible: true,
            value: "ski_snowboard_ticket",
            _id: "600a53b79dc3017cc561768f",
          },
          { eligible: true, value: "athletic_event_fee", _id: "600a53b79dc3017cc5617690" },
          { eligible: true, value: "sports_league_fee", _id: "600a53b79dc3017cc5617691" },
        ],
        _id: "600a53b79dc3017cc561768e",
      },
      {
        id: "digital_health_apps",
        name: "Digital Health Apps",
        subcategories: [
          { eligible: true, value: "meditation_app", _id: "600a53b79dc3017cc5617693" },
          { eligible: true, value: "seep_aid_app", _id: "600a53b79dc3017cc5617694" },
          { eligible: true, value: "fitness_app", _id: "600a53b79dc3017cc5617695" },
        ],
        _id: "600a53b79dc3017cc5617692",
      },
      {
        id: "equipment",
        name: "Equipment",
        subcategories: [
          { eligible: true, value: "sports_equipment", _id: "600a53b79dc3017cc5617697" },
          {
            eligible: true,
            value: "fitness_equipment",
            _id: "600a53b79dc3017cc5617698",
          },
          {
            eligible: true,
            value: "equipment_others",
            _id: "600a53b79dc3017cc5617699",
          },
          {
            eligible: true,
            value: "equipment_rental",
            _id: "600a53b79dc3017cc561769a",
          },
          {
            eligible: false,
            value: "motorized_vehicles",
            _id: "600a53b79dc3017cc561769b",
          },
        ],
        _id: "600a53b79dc3017cc5617696",
      },
      {
        id: "general_health",
        name: "General Health",
        subcategories: [
          { _id: "600a53b79dc3017cc561769d", value: "acupuncture", eligible: false },
          { _id: "600a53b79dc3017cc561769e", value: "massage_therapy", eligible: true },
          { _id: "600a53b79dc3017cc561769f", value: "alternative_health", eligible: true },
          { _id: "600a53b79dc3017cc56176a0", value: "spa_sauna", eligible: true },
          { _id: "600a53b79dc3017cc56176a1", value: "smoking_cessation", eligible: true },
          { _id: "600a53b79dc3017cc56176a2", value: "weight_management", eligible: true },
          { _id: "600a53b79dc3017cc56176a3", value: "primary_care_substitute", eligible: false },
          { _id: "600a53b79dc3017cc56176a4", value: "general_health_others", eligible: false },
          { _id: "600a53b79dc3017cc56176a5", value: "meditation", eligible: true },
          { _id: "600a53b79dc3017cc56176a6", value: "mental_health_consulting", eligible: true },
        ],
        _id: "600a53b79dc3017cc561769c",
      },
      {
        id: "smart_devices",
        name: "Smart Devices",
        subcategories: [
          { _id: "600a53b79dc3017cc56176a8", value: "smart_watch", eligible: false },
          { _id: "600a53b79dc3017cc56176a9", value: "fitness_tracker", eligible: true },
          { _id: "600a53b79dc3017cc56176aa", value: "sleep_tracker", eligible: true },
          { _id: "600a53b79dc3017cc56176ab", value: "body_scale", eligible: true },
        ],
        _id: "600a53b79dc3017cc56176a7",
      },
      {
        id: "nutrition",
        name: "Nutrition",
        subcategories: [
          { _id: "600a53b79dc3017cc56176ad", value: "food", eligible: false },
          { _id: "600a53b79dc3017cc56176ae", value: "convenience_food", eligible: false },
          { _id: "600a53b79dc3017cc56176af", value: "supplements", eligible: false },
        ],
        _id: "600a53b79dc3017cc56176ac",
      },
      {
        id: "others",
        name: "Others",
        subcategories: [
          { _id: "600a53b79dc3017cc56176b1", value: "personal_enrichment", eligible: false },
          { _id: "600a53b79dc3017cc56176b2", value: "clothes", eligible: false },
          { _id: "600a53b79dc3017cc56176b3", value: "shoes", eligible: false },
          { _id: "600a53b79dc3017cc56176b4", value: "books_magazines", eligible: false },
        ],
        _id: "600a53b79dc3017cc56176b0",
      },
    ],
    companyWalletConfigurationId: "twic_wellness",
    defaultCategories: [
      "gym",
      "massage",
      "wearables",
      "testing_kits",
      "meditation_class",
      "digital_health_apps",
      "nutrition_programs",
      "weight_loss_programs",
      "fitness_classes",
      "personal_training",
      "sports_club_membership",
      "martial_arts",
      "stress_management_program",
      "sleep_management_program",
      "smoking_cessation_program",
      "health_programs",
      "mindfulness",
      "gym_and_fitness",
      "sports_and_activities",
      "smart_devices",
      "home_office_equipment",
      "parenting",
      "nutrition",
    ],
    description: "Take care of your health and wellbeing",
    expiredAmount: 3076.96,
    expiredDate: "Feb 21, 2021",
    fundsExpireDays: -120,
    isTwicCardPaymentAllowed: true,
    maxAmount: 3076.96,
    name: "wellness wallet",
    renewedAmount: 50,
    renewedDate: "Feb 22, 2021",
    unit: "$",
    walletId: "twic_max_account_wallet_01",
    walletTypeId: "wellness",
  },
  category: "gym_and_fitness",
};
export const formattedSubCategoriesResponse = ["subcategories:personal_training", "subcategories:gym", "subcategories:fitness_class", "subcategories:fitness_others"];

export const formattedCommonQueryParams = {
  subcategoriesQuery: "AND (subcategories:personal_training OR subcategories:gym OR subcategories:fitness_class OR subcategories:fitness_others)",
  walletBlackListedVendors: "",
  country: "us",
};
export const formattedCommonQueryResponse = "is_product_active:true AND is_vendor_active:true AND available_countries:us    AND (subcategories:personal_training OR subcategories:gym OR subcategories:fitness_class OR subcategories:fitness_others)";

export const formattedBlackListedVendorsQueryParams = {
  wallets: [
    {
      name: "wellness wallet",
      description: "Take care of your health and wellbeing",
      brandingColor: "#E57370",
      categories: [
        {
          _id: "600a53b79dc3017cc5617689",
          id: "gym_and_fitness",
          name: "Gym & Fitness",
          subcategories: [
            {
              _id: "600a53b79dc3017cc561768a",
              value: "personal_training",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc561768b",
              value: "gym",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc561768c",
              value: "fitness_class",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc561768d",
              value: "fitness_others",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc561768e",
          id: "sports_and_activities",
          name: "Sports & Activities",
          subcategories: [
            {
              _id: "600a53b79dc3017cc561768f",
              value: "ski_snowboard_ticket",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc5617690",
              value: "athletic_event_fee",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc5617691",
              value: "sports_league_fee",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc5617692",
          id: "digital_health_apps",
          name: "Digital Health Apps",
          subcategories: [
            {
              _id: "600a53b79dc3017cc5617693",
              value: "meditation_app",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc5617694",
              value: "seep_aid_app",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc5617695",
              value: "fitness_app",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc5617696",
          id: "equipment",
          name: "Equipment",
          subcategories: [
            {
              _id: "600a53b79dc3017cc5617697",
              value: "sports_equipment",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc5617698",
              value: "fitness_equipment",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc5617699",
              value: "equipment_others",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc561769a",
              value: "equipment_rental",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc561769b",
              value: "motorized_vehicles",
              eligible: false,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc561769c",
          id: "general_health",
          name: "General Health",
          subcategories: [
            {
              _id: "600a53b79dc3017cc561769d",
              value: "acupuncture",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc561769e",
              value: "massage_therapy",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc561769f",
              value: "alternative_health",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc56176a0",
              value: "spa_sauna",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc56176a1",
              value: "smoking_cessation",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc56176a2",
              value: "weight_management",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc56176a3",
              value: "primary_care_substitute",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc56176a4",
              value: "general_health_others",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc56176a5",
              value: "meditation",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc56176a6",
              value: "mental_health_consulting",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc56176a7",
          id: "smart_devices",
          name: "Smart Devices",
          subcategories: [
            {
              _id: "600a53b79dc3017cc56176a8",
              value: "smart_watch",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc56176a9",
              value: "fitness_tracker",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc56176aa",
              value: "sleep_tracker",
              eligible: true,
            },
            {
              _id: "600a53b79dc3017cc56176ab",
              value: "body_scale",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc56176ac",
          id: "nutrition",
          name: "Nutrition",
          subcategories: [
            {
              _id: "600a53b79dc3017cc56176ad",
              value: "food",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc56176ae",
              value: "convenience_food",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc56176af",
              value: "supplements",
              eligible: false,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc56176b0",
          id: "others",
          name: "Others",
          subcategories: [
            {
              _id: "600a53b79dc3017cc56176b1",
              value: "personal_enrichment",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc56176b2",
              value: "clothes",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc56176b3",
              value: "shoes",
              eligible: false,
            },
            {
              _id: "600a53b79dc3017cc56176b4",
              value: "books_magazines",
              eligible: false,
            },
          ],
        },
      ],
      isTwicCardPaymentAllowed: true,
      amount: 3076.96,
      maxAmount: 3076.96,
      unit: "$",
      renewedAmount: 50,
      renewedDate: "Feb 22, 2021",
      expiredAmount: 3076.96,
      expiredDate: "Feb 21, 2021",
      fundsExpireDays: -120,
      walletId: "twic_max_account_wallet_01",
      companyWalletConfigurationId: "twic_wellness",
      blackListedVendors: [],
      walletTypeId: "wellness",
      defaultCategories: [
        "gym",
        "massage",
        "wearables",
        "testing_kits",
        "meditation_class",
        "digital_health_apps",
        "nutrition_programs",
        "weight_loss_programs",
        "fitness_classes",
        "personal_training",
        "sports_club_membership",
        "martial_arts",
        "stress_management_program",
        "sleep_management_program",
        "smoking_cessation_program",
        "health_programs",
        "mindfulness",
        "gym_and_fitness",
        "sports_and_activities",
        "smart_devices",
        "home_office_equipment",
        "parenting",
        "nutrition",
      ],
    },
    {
      name: "COVID Care Wallet",
      description: "Covid helpline",
      brandingColor: "#304FFE",
      categories: [
        {
          _id: "600a53b79dc3017cc561763d",
          id: "public_transit_pass",
          name: "public_transit_pass",
          subcategories: [
            {
              _id: "600a53b79dc3017cc561763e",
              value: "public_transit_pass",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc561763f",
          id: "parking_fees",
          name: "parking_fees",
          subcategories: [
            {
              _id: "600a53b79dc3017cc5617640",
              value: "parking_fees",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc5617641",
          id: "vanpools",
          name: "vanpools",
          subcategories: [
            {
              _id: "600a53b79dc3017cc5617642",
              value: "vanpools",
              eligible: true,
            },
          ],
        },
      ],
      isTwicCardPaymentAllowed: true,
      amount: 0,
      maxAmount: 50,
      unit: "$",
      renewedAmount: 50,
      renewedDate: "Feb 22, 2021",
      expiredAmount: 0,
      expiredDate: "Feb 21, 2021",
      fundsExpireDays: -120,
      walletId: "twic_max_account_wallet_02",
      companyWalletConfigurationId: "twic_custom1",
      blackListedVendors: [],
      walletTypeId: "custom",
      defaultCategories: [],
    },
    {
      name: "Biannual Wallet",
      description: "Wallet to check multiple wallets of same type ID",
      brandingColor: "#DD2C00",
      categories: [
        {
          _id: "600a53b79dc3017cc5617644",
          id: "public_transit_pass",
          name: "public_transit_pass",
          subcategories: [
            {
              _id: "600a53b79dc3017cc5617645",
              value: "public_transit_pass",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc5617646",
          id: "parking_fees",
          name: "parking_fees",
          subcategories: [
            {
              _id: "600a53b79dc3017cc5617647",
              value: "parking_fees",
              eligible: true,
            },
          ],
        },
        {
          _id: "600a53b79dc3017cc5617648",
          id: "vanpools",
          name: "vanpools",
          subcategories: [
            {
              _id: "600a53b79dc3017cc5617649",
              value: "vanpools",
              eligible: true,
            },
          ],
        },
      ],
      isTwicCardPaymentAllowed: true,
      amount: 150,
      maxAmount: 500,
      unit: "$",
      renewedAmount: 150,
      renewedDate: "Feb 22, 2021",
      expiredAmount: 150,
      expiredDate: "Feb 21, 2021",
      fundsExpireDays: -120,
      walletId: "twic_max_account_wallet_03",
      companyWalletConfigurationId: "twic_custom2",
      blackListedVendors: [],
      walletTypeId: "custom",
      defaultCategories: [],
    },
    {
      name: "Rewards Wallet",
      description: "Take care of your health and wellbeing",
      brandingColor: "#E57370",
      categories: [],
      isTwicCardPaymentAllowed: true,
      amount: 9762.38,
      maxAmount: 9762.38,
      unit: "$",
      renewedAmount: 50,
      renewedDate: "Jan 1, 2022",
      expiredAmount: 9762.38,
      expiredDate: "Dec 31, 2021",
      fundsExpireDays: 193,
      walletId: "ddaac323-6b06-41fb-bf7e-43c60e444ac7",
      companyWalletConfigurationId: "twic_rewards",
      blackListedVendors: [],
      walletTypeId: "rewards",
      defaultCategories: [],
    },
    {
      name: "custom daily wallet",
      description: "Makes going to work easier",
      brandingColor: "#E57370",
      categories: [],
      isTwicCardPaymentAllowed: true,
      amount: 0,
      maxAmount: 10,
      unit: "$",
      renewedAmount: 10,
      renewedDate: "Jan 22, 2021",
      expiredAmount: 0,
      expiredDate: "Jan 21, 2021",
      fundsExpireDays: -151,
      walletId: "66c02b1a-8a5a-4d2c-a9c1-edd2c5ae22f9",
      companyWalletConfigurationId: "twic_daily",
      blackListedVendors: [],
      walletTypeId: "custom",
      defaultCategories: [],
    },
    {
      name: "pet weekly wallet",
      description: "Makes going to work easier",
      brandingColor: "#E57370",
      categories: [],
      isTwicCardPaymentAllowed: true,
      amount: 0,
      maxAmount: 20,
      unit: "$",
      renewedAmount: 20,
      renewedDate: "Jan 18, 2021",
      expiredAmount: 0,
      expiredDate: "Jan 17, 2021",
      fundsExpireDays: -155,
      walletId: "fce206b3-3089-4d62-9edf-b50fbd956465",
      companyWalletConfigurationId: "twic_weekly",
      blackListedVendors: [],
      walletTypeId: "pet",
      defaultCategories: [],
    },
  ],
  wallet: {
    name: "wellness wallet",
    description: "Take care of your health and wellbeing",
    brandingColor: "#E57370",
    categories: [
      {
        _id: "600a53b79dc3017cc5617689",
        id: "gym_and_fitness",
        name: "Gym & Fitness",
        subcategories: [
          {
            _id: "600a53b79dc3017cc561768a",
            value: "personal_training",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc561768b",
            value: "gym",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc561768c",
            value: "fitness_class",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc561768d",
            value: "fitness_others",
            eligible: true,
          },
        ],
      },
      {
        _id: "600a53b79dc3017cc561768e",
        id: "sports_and_activities",
        name: "Sports & Activities",
        subcategories: [
          {
            _id: "600a53b79dc3017cc561768f",
            value: "ski_snowboard_ticket",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc5617690",
            value: "athletic_event_fee",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc5617691",
            value: "sports_league_fee",
            eligible: true,
          },
        ],
      },
      {
        _id: "600a53b79dc3017cc5617692",
        id: "digital_health_apps",
        name: "Digital Health Apps",
        subcategories: [
          {
            _id: "600a53b79dc3017cc5617693",
            value: "meditation_app",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc5617694",
            value: "seep_aid_app",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc5617695",
            value: "fitness_app",
            eligible: true,
          },
        ],
      },
      {
        _id: "600a53b79dc3017cc5617696",
        id: "equipment",
        name: "Equipment",
        subcategories: [
          {
            _id: "600a53b79dc3017cc5617697",
            value: "sports_equipment",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc5617698",
            value: "fitness_equipment",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc5617699",
            value: "equipment_others",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc561769a",
            value: "equipment_rental",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc561769b",
            value: "motorized_vehicles",
            eligible: false,
          },
        ],
      },
      {
        _id: "600a53b79dc3017cc561769c",
        id: "general_health",
        name: "General Health",
        subcategories: [
          {
            _id: "600a53b79dc3017cc561769d",
            value: "acupuncture",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc561769e",
            value: "massage_therapy",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc561769f",
            value: "alternative_health",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc56176a0",
            value: "spa_sauna",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc56176a1",
            value: "smoking_cessation",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc56176a2",
            value: "weight_management",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc56176a3",
            value: "primary_care_substitute",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc56176a4",
            value: "general_health_others",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc56176a5",
            value: "meditation",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc56176a6",
            value: "mental_health_consulting",
            eligible: true,
          },
        ],
      },
      {
        _id: "600a53b79dc3017cc56176a7",
        id: "smart_devices",
        name: "Smart Devices",
        subcategories: [
          {
            _id: "600a53b79dc3017cc56176a8",
            value: "smart_watch",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc56176a9",
            value: "fitness_tracker",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc56176aa",
            value: "sleep_tracker",
            eligible: true,
          },
          {
            _id: "600a53b79dc3017cc56176ab",
            value: "body_scale",
            eligible: true,
          },
        ],
      },
      {
        _id: "600a53b79dc3017cc56176ac",
        id: "nutrition",
        name: "Nutrition",
        subcategories: [
          {
            _id: "600a53b79dc3017cc56176ad",
            value: "food",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc56176ae",
            value: "convenience_food",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc56176af",
            value: "supplements",
            eligible: false,
          },
        ],
      },
      {
        _id: "600a53b79dc3017cc56176b0",
        id: "others",
        name: "Others",
        subcategories: [
          {
            _id: "600a53b79dc3017cc56176b1",
            value: "personal_enrichment",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc56176b2",
            value: "clothes",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc56176b3",
            value: "shoes",
            eligible: false,
          },
          {
            _id: "600a53b79dc3017cc56176b4",
            value: "books_magazines",
            eligible: false,
          },
        ],
      },
    ],
    isTwicCardPaymentAllowed: true,
    amount: 3076.96,
    maxAmount: 3076.96,
    unit: "$",
    renewedAmount: 50,
    renewedDate: "Feb 22, 2021",
    expiredAmount: 3076.96,
    expiredDate: "Feb 21, 2021",
    fundsExpireDays: -120,
    walletId: "twic_max_account_wallet_01",
    companyWalletConfigurationId: "twic_wellness",
    blackListedVendors: [],
    walletTypeId: "wellness",
    defaultCategories: [
      "gym",
      "massage",
      "wearables",
      "testing_kits",
      "meditation_class",
      "digital_health_apps",
      "nutrition_programs",
      "weight_loss_programs",
      "fitness_classes",
      "personal_training",
      "sports_club_membership",
      "martial_arts",
      "stress_management_program",
      "sleep_management_program",
      "smoking_cessation_program",
      "health_programs",
      "mindfulness",
      "gym_and_fitness",
      "sports_and_activities",
      "smart_devices",
      "home_office_equipment",
      "parenting",
      "nutrition",
    ],
  },
};
export const formattedBlackListedVendorsQueryResponse = "";
export const formattedSubCategoriesQueryParams = ["subcategories:personal_training", "subcategories:gym", "subcategories:fitness_class", "subcategories:fitness_others"];
export const formattedSubCategoriesQueryResponse = "AND (subcategories:personal_training OR subcategories:gym OR subcategories:fitness_class OR subcategories:fitness_others)";
