const TOGGLE_APP_LOADING = "TOGGLE_APP_LOADING";
const RESET_APP_LOADING = "RESET_APP_LOADING";
const SET_FITNESS_AUTHORIZATION = "SET_FITNESS_AUTHORIZATION";
const SET_APP_CURRENT_STACK = "SET_APP_CURRENT_STACK";

const USER_ACTIONS = {
  UPDATE_LOGIN_STATE: "UPDATE_LOGIN_STATE",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  SET_USER_PAYMENT_INFO: "SET_USER_PAYMENT_INFO",
  SET_USER_NOTIFICATION_SETTINGS: "SET_USER_NOTIFICATION_SETTINGS",
  SET_TWIC_CARD_INFO: "SET_TWIC_CARD_INFO",
  SET_PRETAX_ACCOUNTS: "SET_PRETAX_ACCOUNTS",
  TOGGLE_LOGIN_LOADING: "TOGGLE_LOGIN_LOADING",
  SET_USER_DEPENDENTS: "SET_USER_DEPENDENTS",
  SET_USER_DEMOGRAPHICS: "SET_USER_DEMOGRAPHICS",
  SET_USER_COUNTRY_STATES: "SET_USER_COUNTRY_STATES"
};

const MARKETPLACE_ACTIONS = {
  SET_VENDORS: "SET_VENDORS",
  SET_VENUE_ACTIVITIES: "SET_VENUE_ACTIVITIES",
};

const TRANSACTION_ACTIONS = {
  SET_TRANSACTIONS_DATA: "SET_TRANSACTIONS_DATA",
};

const CHALLENGES_ACTIONS = {
  SET_CHALLENGES_DATA: "SET_CHALLENGES_DATA",
  SET_CURRENT_CHALLENGE_DATA: "SET_CURRENT_CHALLENGE_DATA",
  TOGGLE_IS_SYNCING: "TOGGLE_IS_SYNCING",
};

export default {
  USER_ACTIONS,
  TOGGLE_APP_LOADING,
  RESET_APP_LOADING,
  MARKETPLACE_ACTIONS,
  TRANSACTION_ACTIONS,
  CHALLENGES_ACTIONS,
  SET_FITNESS_AUTHORIZATION,
  SET_APP_CURRENT_STACK,
};
