require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'

platform :ios, '11.0'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  pod 'Plaid', '2.0.9' 
  pod 'BraintreeDropIn', :inhibit_warnings => true

target 'joinforma' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'joinformaTests' do
    inherit! :complete
    # Pods for testing
  end

  # use_native_modules!  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({
  'Flipper' => '0.75.1',
  'Flipper-DoubleConversion' => '1.1.7',
  'Flipper-Folly' => '2.5.3',
  'Flipper-Glog' => '0.3.6',
  'Flipper-PeerTalk' => '0.0.4',
  'Flipper-RSocket' => '1.3.1',
  'FlipperKit' => '0.75.1',
  'FlipperKit/Core' => '0.75.1',
  'FlipperKit/CppBridge' => '0.75.1',
  'FlipperKit/FBCxxFollyDynamicConvert' => '0.75.1',
  'FlipperKit/FBDefines' => '0.75.1',
  'FlipperKit/FKPortForwarding' => '0.75.1',
  'FlipperKit/FlipperKitHighlightOverlay' => '0.75.1',
  'FlipperKit/FlipperKitLayoutPlugin' => '0.75.1',
  'FlipperKit/FlipperKitLayoutTextSearchable' => '0.75.1',
  'FlipperKit/FlipperKitNetworkPlugin' => '0.75.1',
  'FlipperKit/FlipperKitReactPlugin' => '0.75.1',
  'FlipperKit/FlipperKitUserDefaultsPlugin' => '0.75.1',
  'FlipperKit/SKIOSNetworkPlugin' => '0.75.1',
})
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == "React-Core-AccessibilityResources"
        target.remove_from_project
      end
    end
  end

end

target 'joinforma-tvOS' do
  # Pods for joinforma-tvOS

  target 'joinforma-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
