export default {
  AUTH_STACK: "Auth",
  AUTH_LOADING: "AuthLoading",
  APP_STACK: "App",
  APP_WITHOUT_MARKETPLACE_STACK: "AppWithoutMarketplace",
  ONBOARDING_STACK: "Onboarding",
  RESET_PASSWORD_SCREEN: "ResetPasswordScreen",

  HOME_SCREEN: "HomeScreen",
  CLAIMS_TAB_SCREEN: "ClaimsTabScreen",
  HOME_SCREEN_WALLET_LISTING: "HomeScreenWalletListingScreen",
  HOME_SCREEN_PRETAX_STORES_LISTING: "HomeScreenPreTaxStoresListingScreen",
  APP_ACCESS_ERROR: "AppAccessErrorScreen",

  LOGIN_SCREEN: "LoginScreen",
  LOGIN_WITH_SSO: "LoginWithSsoScreen",
  LOGIN_WITH_MAGIC_LINK: "LoginWithMagicLinkScreen",
  PASSWORD_SCREEN: "PasswordScreen",
  AUTH_SELECTION_SCREEN: "AuthSelectionScreen",

  ONBOARDING_NOTIFICATION: "NotificationsScreen",
  POSTTAX_LISTING_SCREEN: "PosttaxListingScreen",
  PRETAX_LISTING_SCREEN: "PretaxListingScreen",
  BENEFITS_SCREEN: "Benefits",
  COMPLETE_PROFILE_SCREEN: "CompleteProfileScreen",

  MERCHANT_LISTING: "MerchantAndCategoryListingScreen",
  MERCHANT_DETAILS: "MerchantDetailsScreen",
  WEB_VIEW: "WebViewScreen",
  FAQS: "FaqsScreen",

  USER_PROFILE: "UserProfileScreen",
  USER_PROFILE_SETTINGS: "UserProfileSettingsScreen",
  // USER_HEALTH: "UserHealthScreen",
  USER_ORDERS: "UserOrdersScreen",
  USER_SUBSCRIPTIONS: "UserSubscriptionsScreen",
  USER_SUBSCRIPTION_DETAIL_SCREEN: "UserSubscriptionDetailScreen",
  USER_ORDER_DETAIL_SCREEN: "UserOrderDetailScreen",
  WALLET_TRANSACTION_DETAIL_SCREEN: "WalletTransactionDetailScreen",
  USER_BANK_ACCOUNT: "UserBankAccountScreen",
  MANUAL_BANK_LINK: "ManualBankLinkScreen",
  MANUAL_BANK_LINK_VERIFICATION: "ManualBankLinkVerificationScreen",
  BANK_CONNECT_WEB_VIEW: "BankConnectWebViewScreen",
  UPDATE_TWIC_CARD_ADDRESS: "UpdateAddressForm",
  REPLACE_PHYSICAL_TWIC_CARD_SCREEN: "ReplacePhysicalTwicCardScreen",
  TWIC_CARD_CONFIRMATION_SCREEN: "TwicCardsConfirmation",
  INITIAL_TWIC_CARDS_CREATE_SCREEN: "AddInitialTwicCardsScreen",
  CREATE_TWIC_CARD: "CreateTwicCard",
  USER_TWIC_CARD: "TwicCardsScreen",
  USER_NOTIFICATIONS_SETTINGS_SCREEN: "UserNotificationsSettingsScreen",
  NOTIFICATION_PERMISSION_SCREEN: "NotificationPermissionScreen",
  PRETAX_CARD_SCREEN: "PretaxCardScreen",
  ADD_PRETAX_CARD_SCREEN: "RequestPreTaxCardScreen",
  UPDATE_DEPENDENTS_SCREEN: "UpdateDependentsScreen",
  REQUEST_PRETAX_CARD_WITH_NEW_DEPENDENT: "RequestPreTaxCardWithNewDependent",
  REQUEST_PRETAX_CARD_WITH_EXISTING_DEPENDENT: "RequestPreTaxCardWithExistingDependent",
  REQUEST_PRETAX_CARD_SUBMMISION_SCREEN: "RequestPreTaxCardSubmissionScreen",
  PRETAX_CARD_SCREEN_WITH_DEPENDENT_CARD: "PretaxCardScreenWithDependentCard",
  SECURITY_SCREEN: "SecurityScreen",

  PRETAX_ACCOUNT_DETAIL_SCREEN: "PreTaxAccountDetailScreen",
  POSTTAX_ACCOUNT_DETAIL_SCREEN: "PostTaxAccountDetailScreen",
  POSTTAX_ACCOUNT_ALL_ACTIVITIES: "PostTaxAllActivities",
  PRETAX_ACCOUNT_ALL_ACTIVITIES: "PreTaxAllActivities",
  GYMS_MAPVIEW: "GymsMapViewScreen",
  CLAIMS_SCREEN: "ClaimsScreen",
  NEW_REIMBURSEMENT: "NewReimbursementScreen",
  PRETAX_EXPENSES: "NewExpenseScreen",
  ADD_NEW_DEPENDENT: "AddDependentScreen",
  CLAIM_SUBMISSION: "ClaimSubmissionScreen",
  EXPENSE_SUBMISSION: "ExpenseSubmissionScreen",
  REIMBURSEMENT_DETAILS: "ReimbursementDetailScreen",
  PRETAX_CLAIMS_DETAILS: "PreTaxClaimDetailScreen",
  POSTTAX_CLAIMS_DETAILS: "PostTaxClaimDetailScreen",
  EXPENSE_DETAILS: "ExpenseDetailScreen",
  PAYMENTS_SCREEN: "PaymentsScreen",

  CHECKOUT_MERCHANT: "CheckoutScreen",

  CHALLENGE_DETAILS: "ChallengeDetailScreen",
  CHALLENGE_LEADERBOARD: "ChallengeLeaderboardScreen",
  SUBSCRIPTIONS_CANCELLATION: "SubscriptionCancellationScreen",
};
